services:
  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:latest
    restart: always
    ports:
      - '80:80/tcp'
    volumes:
      - ./mainsail-config.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - printer