services:
  printer:
    image: ghcr.io/mainsail-crew/virtual-klipper-printer:latest
    container_name: printer
    volumes:
      - ./printer_data:/home/printer/printer_data:delegated,Z
    ports:
      - "7125:7125"
      - "8110:8080"
    tmpfs:
      - /tmp:noexec
      - /home/printer/printer_data/comms:noexec
    
  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:latest
    restart: always
    ports:
      - '80:80/tcp'
    volumes:
      - ./mainsail-config.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - printer
