services:
  printer:
    image: virtual-klipper-printer-moonraker:local
    container_name: printer
    volumes:
      - ./printer_data:/home/printer/printer_data:delegated,Z
    ports:
      - "7125:7125"
      - "8110:8080"
    tmpfs:
      - /tmp:noexec
      - /home/printer/printer_data/comms:noexec
