services:
  printer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KLIPPER_REPO: ${KLIPPER_REPO:-https://github.com/Klipper3d/klipper.git}
    image: ghcr.io/joostm8/virtual-klipper-octoprint:latest
    container_name: printer
    volumes:
      - ./printer_data:/home/printer/printer_data:delegated,Z
      - ./printer_data/octoprint:/octoprint
    ports:
      - "5000:5000"
      - "8110:8080"
    tmpfs:
      - /tmp:noexec
      - /home/printer/printer_data/comms:noexec

  mosquitto:
    image: joostm8/mosquitto-anonymous-allowed
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./docker-data/mosquitto/data:/mosquitto/data
      - ./docker-data/mosquitto/log:/mosquitto/log
    networks:
      default:
        aliases:
          - broker
